SYSROOT=$(shell pwd)/sysroot

# flags
QEMUFLAGS = -no-reboot -D /tmp/qemu.log -d cpu_reset,guest_errors,int,in_asm
LDFLAGS   = -Wl,-Map=kernel.map -ffreestanding

CFLAGS = -ffreestanding -Wall -Wextra -Wno-unused-variable -Wno-unused-function -Wno-pointer-to-int-cast -Wno-unused
CFLAGS := $(CFLAGS) -g -O0 -Iinclude -Wshadow -nodefaultlibs -D__amd64__

# Subsystems
ARCHDIR=arch/amd64
DRIVERDIR=drivers
LIBRARYDIR=lib
MMUDIR=mm

# sysroot related directories
BOOTDIR=/boot
INCLUDEDIR=/usr/include
LIBDIR=/usr/lib

AR=x86_64-elf-ar
AS=x86_64-elf-as
CC=x86_64-elf-gcc -isystem=$(INCLUDEDIR)
